const { connect, collections, close, DB_NAME } = require("../src/db");
const { validateEnv } = require("../src/config/env");

const NEW_DOCTORS = [
  {
    name: "Dr. Tanvir Ahmed",
    specialty: "Cardiologist",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    experience: "12 years",
    availability: ["09:00 AM - 12:00 PM", "04:00 PM - 07:00 PM"],
    description:
      "Interventional cardiologist specializing in angioplasty, heart failure management, and preventive cardiology for high-risk patients.",
    hospital: "Evercare Hospital",
    location: "Bashundhara, Dhaka",
    fee: 1200,
    rating: 4.8,
    totalReviews: 214,
    education: "MBBS, MD (Cardiology) – BSMMU, Dhaka",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-02-14T08:00:00Z",
  },
  {
    name: "Dr. Salma Khatun",
    specialty: "Gynecologist",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    experience: "11 years",
    availability: ["10:00 AM - 01:00 PM", "05:00 PM - 08:00 PM"],
    description:
      "Specialist in high-risk pregnancy care, infertility treatment, and minimally invasive gynecologic surgery.",
    hospital: "Square Hospital",
    location: "Panthapath, Dhaka",
    fee: 900,
    rating: 4.9,
    totalReviews: 187,
    education: "MBBS, FCPS (Obstetrics & Gynaecology) – Dhaka Medical College",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-02-08T08:00:00Z",
  },
  {
    name: "Dr. Imran Hossain",
    specialty: "Neurologist",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    experience: "14 years",
    availability: ["08:00 AM - 11:00 AM", "03:00 PM - 06:00 PM"],
    description:
      "Neurologist focused on stroke care, epilepsy management, headache disorders, and neuro-degenerative diseases.",
    hospital: "United Hospital",
    location: "Gulshan, Dhaka",
    fee: 1100,
    rating: 4.7,
    totalReviews: 152,
    education: "MBBS, MD (Neurology) – Bangabandhu Sheikh Mujib Medical University",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-02-20T08:00:00Z",
  },
  {
    name: "Dr. Farhana Yasmin",
    specialty: "Dermatologist",
    image: "https://randomuser.me/api/portraits/women/13.jpg",
    experience: "8 years",
    availability: ["11:00 AM - 02:00 PM", "06:00 PM - 09:00 PM"],
    description:
      "Dermatologist specializing in acne, eczema, psoriasis, cosmetic dermatology, and laser treatments.",
    hospital: "Ibn Sina Diagnostic Center",
    location: "Dhanmondi, Dhaka",
    fee: 700,
    rating: 4.6,
    totalReviews: 98,
    education: "MBBS, FCPS (Dermatology) – Dhaka Medical College",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-03-02T08:00:00Z",
  },
  {
    name: "Dr. Mahmudul Hasan",
    specialty: "Orthopedic",
    image: "https://randomuser.me/api/portraits/men/14.jpg",
    experience: "15 years",
    availability: ["09:00 AM - 12:00 PM", "02:00 PM - 05:00 PM"],
    description:
      "Orthopedic surgeon specializing in joint replacement, sports injuries, spinal disorders, and trauma care.",
    hospital: "Apollo Hospital",
    location: "Basundhara, Dhaka",
    fee: 1000,
    rating: 4.8,
    totalReviews: 241,
    education: "MBBS, MS (Orthopedics) – Dhaka Medical College",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-03-05T08:00:00Z",
  },
  {
    name: "Dr. Nazia Sultana",
    specialty: "Pediatrician",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
    experience: "9 years",
    availability: ["10:00 AM - 01:00 PM", "04:00 PM - 07:00 PM"],
    description:
      "Child specialist focusing on newborn care, vaccinations, growth monitoring, and childhood infections.",
    hospital: "Ad-din Hospital",
    location: "Maghbazar, Dhaka",
    fee: 600,
    rating: 4.9,
    totalReviews: 173,
    education: "MBBS, MD (Pediatrics) – Dhaka Shishu Hospital",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-03-10T08:00:00Z",
  },
  {
    name: "Dr. Rezaul Karim",
    specialty: "ENT Specialist",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    experience: "10 years",
    availability: ["09:00 AM - 01:00 PM", "05:00 PM - 08:00 PM"],
    description:
      "ENT surgeon specializing in sinus surgery, hearing disorders, tonsillectomy, and vertigo management.",
    hospital: "Popular Diagnostic Center",
    location: "Dhanmondi, Dhaka",
    fee: 750,
    rating: 4.5,
    totalReviews: 121,
    education: "MBBS, FCPS (ENT) – Dhaka Medical College",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-03-15T08:00:00Z",
  },
  {
    name: "Dr. Shirin Akter",
    specialty: "Ophthalmologist",
    image: "https://randomuser.me/api/portraits/women/15.jpg",
    experience: "13 years",
    availability: ["08:00 AM - 12:00 PM", "03:00 PM - 06:00 PM"],
    description:
      "Eye surgeon specializing in cataract surgery, LASIK, glaucoma management, and diabetic retinopathy.",
    hospital: "Bangladesh Eye Hospital",
    location: "Mohakhali, Dhaka",
    fee: 850,
    rating: 4.8,
    totalReviews: 165,
    education: "MBBS, DO, FCPS (Ophthalmology) – BSMMU",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-03-18T08:00:00Z",
  },
  {
    name: "Dr. Arif Chowdhury",
    specialty: "Pulmonologist",
    image: "https://randomuser.me/api/portraits/men/16.jpg",
    experience: "11 years",
    availability: ["10:00 AM - 01:00 PM", "05:00 PM - 08:00 PM"],
    description:
      "Chest specialist managing asthma, COPD, tuberculosis, sleep apnea, and respiratory infections.",
    hospital: "National Institute of Diseases of the Chest & Hospital",
    location: "Mohakhali, Dhaka",
    fee: 800,
    rating: 4.6,
    totalReviews: 134,
    education: "MBBS, FCPS (Chest Diseases) – NICRH",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-03-22T08:00:00Z",
  },
  {
    name: "Dr. Mitu Rahman",
    specialty: "Psychiatrist",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
    experience: "9 years",
    availability: ["11:00 AM - 02:00 PM", "06:00 PM - 09:00 PM"],
    description:
      "Psychiatrist specializing in depression, anxiety disorders, OCD, stress management, and child psychiatry.",
    hospital: "National Institute of Mental Health",
    location: "Sher-e-Bangla Nagar, Dhaka",
    fee: 650,
    rating: 4.7,
    totalReviews: 89,
    education: "MBBS, MD (Psychiatry) – NIMH, Dhaka",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-03-28T08:00:00Z",
  },
  {
    name: "Dr. Ashraful Islam",
    specialty: "Gastroenterologist",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
    experience: "12 years",
    availability: ["09:00 AM - 12:00 PM", "03:00 PM - 06:00 PM"],
    description:
      "Liver and digestive disease specialist performing endoscopy, colonoscopy, and hepatitis C treatment.",
    hospital: "Birdem General Hospital",
    location: "Shahbagh, Dhaka",
    fee: 950,
    rating: 4.7,
    totalReviews: 145,
    education: "MBBS, FCPS (Gastroenterology) – BSMMU",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-04-02T08:00:00Z",
  },
  {
    name: "Dr. Jannatul Ferdous",
    specialty: "Nephrologist",
    image: "https://randomuser.me/api/portraits/women/17.jpg",
    experience: "10 years",
    availability: ["10:00 AM - 01:00 PM", "04:00 PM - 07:00 PM"],
    description:
      "Kidney specialist managing chronic kidney disease, dialysis, hypertension, and renal transplantation follow-up.",
    hospital: "Kidney Hospital",
    location: "Mirpur, Dhaka",
    fee: 900,
    rating: 4.6,
    totalReviews: 76,
    education: "MBBS, MD (Nephrology) – BSMMU",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-04-05T08:00:00Z",
  },
  {
    name: "Dr. Shakil Ahmed",
    specialty: "Urologist",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
    experience: "11 years",
    availability: ["08:00 AM - 11:00 AM", "02:00 PM - 05:00 PM"],
    description:
      "Urological surgeon specializing in kidney stones, prostate disorders, and minimally invasive urologic surgery.",
    hospital: "National Institute of Kidney Diseases & Urology",
    location: "Sher-e-Bangla Nagar, Dhaka",
    fee: 850,
    rating: 4.5,
    totalReviews: 112,
    education: "MBBS, MS (Urology) – NIKDU",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-04-10T08:00:00Z",
  },
  {
    name: "Dr. Parvin Sultana",
    specialty: "Endocrinologist",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
    experience: "10 years",
    availability: ["10:00 AM - 01:00 PM", "05:00 PM - 08:00 PM"],
    description:
      "Hormone specialist managing diabetes, thyroid disorders, PCOS, and metabolic bone diseases.",
    hospital: "BIRDEM General Hospital",
    location: "Shahbagh, Dhaka",
    fee: 800,
    rating: 4.8,
    totalReviews: 158,
    education: "MBBS, MD (Endocrinology) – BSMMU",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-04-15T08:00:00Z",
  },
  {
    name: "Dr. Hasan Mahmud",
    specialty: "Oncologist",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
    experience: "13 years",
    availability: ["09:00 AM - 12:00 PM", "03:00 PM - 06:00 PM"],
    description:
      "Medical oncologist specializing in chemotherapy, targeted therapy, and immunotherapy for solid tumors.",
    hospital: "Ahsania Mission Cancer Hospital",
    location: "Uttara, Dhaka",
    fee: 1100,
    rating: 4.7,
    totalReviews: 102,
    education: "MBBS, FCPS (Oncology) – NICRH",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-04-20T08:00:00Z",
  },
  {
    name: "Dr. Rubina Aktar",
    specialty: "Hematologist",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
    experience: "9 years",
    availability: ["11:00 AM - 02:00 PM", "04:00 PM - 07:00 PM"],
    description:
      "Blood disorder specialist managing thalassemia, anemia, clotting disorders, and hematologic malignancies.",
    hospital: "Thalassemia Foundation Hospital",
    location: "Bashundhara, Dhaka",
    fee: 750,
    rating: 4.6,
    totalReviews: 68,
    education: "MBBS, FCPS (Hematology) – BSMMU",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-04-25T08:00:00Z",
  },
  {
    name: "Dr. Ziaur Rahman",
    specialty: "Rheumatologist",
    image: "https://randomuser.me/api/portraits/men/20.jpg",
    experience: "11 years",
    availability: ["09:00 AM - 12:00 PM", "05:00 PM - 08:00 PM"],
    description:
      "Joint and autoimmune disease specialist treating rheumatoid arthritis, lupus, gout, and osteoporosis.",
    hospital: "Bangabandhu Sheikh Mujib Medical University",
    location: "Shahbagh, Dhaka",
    fee: 900,
    rating: 4.5,
    totalReviews: 84,
    education: "MBBS, FCPS (Rheumatology) – BSMMU",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-05-01T08:00:00Z",
  },
  {
    name: "Dr. Nabil Hasan",
    specialty: "Dentist",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
    experience: "8 years",
    availability: ["10:00 AM - 02:00 PM", "05:00 PM - 09:00 PM"],
    description:
      "Dental surgeon specializing in root canal treatment, dental implants, braces, and cosmetic dentistry.",
    hospital: "Dhaka Dental College",
    location: "Mirpur, Dhaka",
    fee: 500,
    rating: 4.7,
    totalReviews: 143,
    education: "BDS, FCPS (Dentistry) – Dhaka Dental College",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-05-05T08:00:00Z",
  },
  {
    name: "Dr. Tasnim Alam",
    specialty: "General Medicine",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    experience: "10 years",
    availability: ["08:00 AM - 12:00 PM", "03:00 PM - 06:00 PM"],
    description:
      "Internal medicine specialist providing comprehensive care for fever, infections, diabetes, and hypertension.",
    hospital: "Green Life Hospital",
    location: "Dhanmondi, Dhaka",
    fee: 600,
    rating: 4.6,
    totalReviews: 176,
    education: "MBBS, FCPS (Medicine) – Dhaka Medical College",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-05-10T08:00:00Z",
  },
  {
    name: "Dr. Fahim Rahman",
    specialty: "Emergency Medicine",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    experience: "9 years",
    availability: ["07:00 AM - 01:00 PM", "02:00 PM - 08:00 PM"],
    description:
      "Emergency physician skilled in critical care, trauma resuscitation, cardiac emergencies, and acute poisoning.",
    hospital: "Dhaka Medical College Hospital",
    location: "Bakshi Bazar, Dhaka",
    fee: 700,
    rating: 4.4,
    totalReviews: 96,
    education: "MBBS, MCPS (Emergency Medicine) – DMCH",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-05-15T08:00:00Z",
  },
  {
    name: "Dr. Rashedul Islam",
    specialty: "Sports Medicine",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
    experience: "8 years",
    availability: ["10:00 AM - 01:00 PM", "04:00 PM - 07:00 PM"],
    description:
      "Sports physician treating muscle injuries, ligament tears, rehabilitation, and performance optimization.",
    hospital: "Bangladesh Krira Shikkha Protisthan",
    location: "Savar, Dhaka",
    fee: 650,
    rating: 4.5,
    totalReviews: 58,
    education: "MBBS, FCPS (Sports Medicine) – BKSP",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-05-20T08:00:00Z",
  },
  {
    name: "Dr. Sharmin Akter",
    specialty: "Radiologist",
    image: "https://randomuser.me/api/portraits/women/21.jpg",
    experience: "10 years",
    availability: ["09:00 AM - 02:00 PM", "04:00 PM - 08:00 PM"],
    description:
      "Radiologist specializing in MRI, CT imaging, ultrasound diagnosis, and image-guided procedures.",
    hospital: "Medinova Diagnostic Center",
    location: "Dhanmondi, Dhaka",
    fee: 800,
    rating: 4.6,
    totalReviews: 91,
    education: "MBBS, FCPS (Radiology) – BSMMU",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-05-25T08:00:00Z",
  },
  {
    name: "Dr. Golam Mostofa",
    specialty: "Anesthesiologist",
    image: "https://randomuser.me/api/portraits/men/24.jpg",
    experience: "12 years",
    availability: ["08:00 AM - 12:00 PM", "02:00 PM - 05:00 PM"],
    description:
      "Anesthesiologist specialized in perioperative care, pain management, and intensive care support.",
    hospital: "Anwer Khan Modern Medical College",
    location: "Dhanmondi, Dhaka",
    fee: 750,
    rating: 4.5,
    totalReviews: 64,
    education: "MBBS, DA, MCPS (Anesthesiology) – BSMMU",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-06-01T08:00:00Z",
  },
  {
    name: "Dr. Labiba Haque",
    specialty: "Cardiologist",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
    experience: "10 years",
    availability: ["09:00 AM - 12:00 PM", "05:00 PM - 08:00 PM"],
    description:
      "Non-invasive cardiologist focusing on echocardiography, arrhythmia management, and heart disease prevention.",
    hospital: "National Heart Foundation Hospital",
    location: "Mirpur, Dhaka",
    fee: 950,
    rating: 4.8,
    totalReviews: 129,
    education: "MBBS, FCPS (Cardiology) – NICVD",
    languages: ["Bengali", "English"],
    isAvailable: true,
    createdAt: "2025-06-05T08:00:00Z",
  },
];

async function seed() {
  validateEnv();
  await connect();
  console.log(`Connected to MongoDB database: ${DB_NAME}`);

  const { doctors } = await collections();
  const existing = await doctors.find({}).toArray();
  const existingNames = new Set(existing.map((doctor) => doctor.name));

  const toInsert = NEW_DOCTORS.filter(
    (doctor) => !existingNames.has(doctor.name),
  );

  if (toInsert.length === 0) {
    console.log("All seed doctors already exist. Nothing to insert.");
  } else {
    await doctors.insertMany(toInsert);
    console.log(`Inserted ${toInsert.length} new doctors.`);
  }

  const total = await doctors.countDocuments();
  console.log(`Total doctors in collection: ${total}`);

  await close();
  process.exit(0);
}

seed().catch((error) => {
  console.error("Seeding failed:", error);
  process.exit(1);
});
